charts/egeria-base/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
=> Increment version for charts after migration

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/requirements.yaml, charts/odpi-egeria-lab/values.yaml
=> Update to align with egeria release 3.0 components

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
=> ensure numeric versions are quoted

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
=> Update pull policy to IfNotPresent for release

charts/egeria-base/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
Updates charts to final release version
=> Update charts to final version 3 release for Egeria

.github/workflows/mkdocs.yml
=> Initial mkdocs

index.html
=> Add redirect for mkdocs

.github/workflows/mkdocs.yml
This reverts commit 33c19dd60fcd22f513fc847232b4cd0cd3ceb53a.
=> Revert "update mkdocs"

.github/workflows/mkdocs.yml, site/mkdocs.yml
=> continued work on mkdocs

index.html
=> updated redirect

.github/workflows/mkdocs.yml
=> updated mkdocs

charts/egeria-base/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
=> increment chart versions to force republish

.github/workflows/mkdocs.yml
=> add clean mkdocs build

.github/workflows/mkdocs.yml
=> Ensure we pull latest docs before pushing doc updates

.github/workflows/mkdocs.yml
=> with full fetch, no need for manual branch switching

index.html
=> update static index.html for redirection

.github/workflows/mkdocs.yml
=> further updates to mkdocs

.github/workflows/mkdocs-verify.yml, .github/workflows/mkdocs.yml
=> Correct github events for pr/main build

site/docs/intro/k8s.md, site/overrides/home.html
=> initial docs on k8s concepts

site/docs/intro/k8s.md
=> further k8s docs

site/docs/charts/lab.md, site/docs/intro/helm.md, site/docs/intro/k8s.md
=> Updated docs for odpi-egeria-lab chart

.github/workflows/mkdocs-verify.yml, .github/workflows/mkdocs.yml
=> Correct names of mkdocs actions

.gitignore, charts/egeria-base/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
Updates final chart versions to 3.1.0
=> Update charts to final version for release 3.1

charts/egeria-base/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
=> Minor increment of chart to address build issue

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
Pre-release charts for the 3.2 release of Egeria
=> Prerelease charts for the Egeria 3.2 release

charts/egeria-base/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
=> Add Appversion to charts to clarify EGERIA version being used

charts/egeria-base/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
=> Update charts to final 3.2.0 release for egeria 3.2

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
* Corrects image versions needed for 3.3
=> #89 correct image versions

charts/egeria-base/Chart.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-pts/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
=> Update to final 3.3 release

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-cts/values.yaml, charts/egeria-pts/Chart.yaml, charts/egeria-pts/values.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
Updates 
- egeria (& misc) to 3.4
- egeria-ui to 3.1.1
- egeria-react-ui to 3.4.0
And delivers initial 3.4.0-prerelease.0 charts for base, lab, cts, pts
=> odpi/egeria#5929 initial prerelease charts for 3.4 release

charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
* Updates static UI version to 3.2.0
=> odpi/egeria#5929 update UI to 3.2.0

charts/egeria-base/Chart.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-pts/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
Updates all charts to 3.4.0 release version
=> odpi/egeria#5929 updates charts to 3.4.0 release version

charts/odpi-egeria-lab/Chart.yaml
Upgrades strimzi as per https://strimzi.io/blog/2021/12/14/strimzi-and-log4shell/ to address vuln
=> #101 Upgrade strimzi to address log4J vuln

charts/egeria-base/Chart.yaml, charts/egeria-base/scripts/config-egeria.sh
* Fixes typo in config script
* increments egeria-base chart version (prerelease)
=> #105 fix typo in config script

charts/egeria-base/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
* Upgrades strimzi to 0.27.0 for egeria-base & odpi-egeria-lab
* Increments pre-release version for testing
=> #101 upgrade strimzi to 0.27.0

charts/egeria-base/Chart.yaml, charts/egeria-base/scripts/config-egeria.sh
Signed-off-by: David Radley <dgradley@gmail.com>
=> #114 add server author config to base chart

README.md, charts/egeria-base/Chart.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-pts/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
=> Update charts to 3.5.0 release

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
Signed-off-by: David Radley <dgradley@gmail.com>
=> git122 update react ui to 3.5

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
Updates charts to 3.6-SNAPSHOT for prerelease
=> Update charts to 3.6 snapshot

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-cts/values.yaml, charts/egeria-pts/Chart.yaml, charts/egeria-pts/values.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
Updates charts to 3.6 (prerelease chart version)
=> odpi/egeria#6228 prerelease charts for 3.6

charts/egeria-base/Chart.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-pts/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
Final release of 3.6 based charts (3.6.0)
=> Update to final 3.6.0 chart release for egeria 3.6

charts/egeria-base/values.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-cts/templates/env.yaml, charts/egeria-cts/templates/init.yaml, charts/egeria-cts/templates/kafka-cluster.yaml, charts/egeria-cts/templates/report.yaml, charts/egeria-cts/templates/serviceaccount.yaml, charts/egeria-cts/values.yaml, charts/egeria-pts/Chart.yaml, charts/egeria-pts/templates/env.yaml, charts/egeria-pts/templates/init.yaml, charts/egeria-pts/templates/kafka-cluster.yaml, charts/egeria-pts/templates/report.yaml, charts/egeria-pts/templates/serviceaccount.yaml, charts/egeria-pts/values.yaml
* Switch kafka implementation to Strimzi (also works on apple silicon, pi & consistent with base/lab)
* Cleanup unneeded values
* Ensure rbac works on non-default namespace
Still to do
* Figure out correct mem/cpu setting (16/32Gb is high)
=> Update CTS/PTS to work on openshift

charts/egeria-cts/Chart.yaml, charts/egeria-cts/scripts/config-egeria.sh, charts/egeria-cts/templates/platform.yaml, charts/egeria-pts/Chart.yaml, charts/egeria-pts/templates/tut.yaml
This change pulls in fixes from PR #124 relating to issue #121 & adds the version increment as per review
- Integrating outstanding PRs prior to release test
=> Fixes LOADER_PATH clobbering

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-cts/values.yaml, charts/egeria-pts/Chart.yaml, charts/egeria-pts/values.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
Updates versions to 3.7 for pre-release testing
=> odpi/egeria#6341 prerelease charts for 3.7

charts/egeria-cts/scripts/config-egeria.sh
Correct where set of metadata collection name is done - was being done too early and failing (though low impact)
=> #138 correct ordering of configuration api calls

charts/egeria-cts/Chart.yaml
Increment cts chart version for publishing (incorrectly omitted on prior PR)
=> #138 increment version for publishing

charts/egeria-base/Chart.yaml, charts/egeria-base/templates/env.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/templates/egeria-presentation.yaml
Skips cert checking in presentation server UI
=> #147 skip cert checking in deployed presentation service

charts/egeria-base/Chart.yaml, charts/egeria-base/templates/env.yaml
=> #147 fix typo in base chart

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-cts/templates/kafka-cluster.yaml, charts/egeria-pts/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
Creates final version for 3.8 release
See https://github.com/odpi/egeria/issues/6435
=> odpi/egeria#6435 final versions for 3.8 release

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-cts/values.yaml, charts/egeria-pts/Chart.yaml, charts/egeria-pts/values.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
Updates for the 3.9 prerelease (for testing)
See odpi/egeria#6539 for more info
=> odpi/egeria#6539 update for 3.9 prerelease charts

charts/egeria-base/Chart.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-pts/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
Updates charts to final 3.9.0 release
=> Update to final 3.9 version

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-cts/values.yaml, charts/egeria-pts/Chart.yaml, charts/egeria-pts/values.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
Updates versions/tags for Charts based on the 3.10 release. Initially prerelease
=> odpi/egeria#6554 pre-release for 3.10

charts/egeria-base/Chart.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-pts/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
Updates chart versions to 3.10.0 - final release
(Merging once new images are available and tested)
=> odpi/egeria#6554 update version to 3.10.0 (final for release)

charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/templates/jupyter.yaml
=> Generate access key for login to jupyter

charts/egeria-base/Chart.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-pts/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
Increment all chart versions due to publish action failing
=> Increment versions again due to chart publishing error in github action

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-cts/values.yaml, charts/egeria-pts/Chart.yaml, charts/egeria-pts/values.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
* Egeria 3.11 
* Strimzi 0.30.0
* versions incremented for prerelease
See odpi/egeria#6812
=> odpi/egeria#6812 update to 3.11 images

charts/egeria-base/Chart.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-pts/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
* Updates all charts to 3.11 release level now that egeria base is released
=> odpi/egeria#6812 Update version to 3.11 release

charts/egeria-base/Chart.yaml
Increments version for publishing
=> #192 increment version for publishing

charts/egeria-base/Chart.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-pts/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
Chart versions updated to 3.12.0 (release)
Had inadvertently been left at prerelease versions
No functional version, but will affect publish to catalog
=> odpi/egeria#6898 update chart versions to 3.12

.github/dependabot.yml
Fix typo (missing line) in dependabot configuration
=> fix dependabot check

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-cts/values.yaml, charts/egeria-pts/Chart.yaml, charts/egeria-pts/values.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
Update chart versions to initial pre-release for 3.13
Signed-off-by: Ljupcho Palashevski <lpalashevski@gmail.com>
=> Charts version 3.13.0-prerelease.0

charts/egeria-base/Chart.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-pts/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
=> Charts version 3.13

charts/egeria-base/Chart.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-pts/Chart.yaml
Updates version across base/cts/pts to synchronize with updated chart-releaser action
=> #178 Update version to sync with new chart-releaser action

charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/scripts/setup-notebooks.sh, charts/odpi-egeria-lab/values.yaml
Corrects bug with switching to specified git clone, when using a shallow clone
=> #178 correct bugs in git clone (do not use shallow)

charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/scripts/setup-notebooks.sh
Minor fix to cleanup if the jupyter pod fails during startup
=> Correct cleanup of jupyter data if fails during setup

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-cts/values.yaml, charts/egeria-pts/Chart.yaml, charts/egeria-pts/values.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
Signed-off-by: Ljupcho Palashevski <lpalashevski@gmail.com>
=> 3.14.0 prerelease 0

charts/egeria-base/Chart.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-pts/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
Signed-off-by: Ljupcho Palashevski <lpalashevski@gmail.com>
=> Charts version 3.14

charts/egeria-base/Chart.yaml, charts/egeria-base/templates/kafka-cluster.yaml, charts/egeria-base/values.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-cts/templates/kafka-cluster.yaml, charts/egeria-cts/values.yaml, charts/egeria-pts/Chart.yaml, charts/egeria-pts/templates/kafka-cluster.yaml, charts/egeria-pts/values.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/templates/kafka-cluster.yaml, charts/odpi-egeria-lab/values.yaml
Updates for the 3.15 release
first pre-release version for testing
=> #7258 update help charts to prerelease version

charts/odpi-egeria-lab/values.yaml
=> #7258 revert to previous jupyter version

charts/odpi-egeria-lab/Chart.yaml
=> #7258 increment lab chart version to republish

charts/egeria-base/Chart.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-pts/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
Signed-off-by: Nigel Jones <nigel.l.jones+git@gmail.com>`
Updates to release version 3.15.0
=> #7258 update to final charts

charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/templates/egeria-core.yaml, charts/odpi-egeria-lab/templates/egeria-datalake.yaml, charts/odpi-egeria-lab/templates/egeria-dev.yaml, charts/odpi-egeria-lab/templates/egeria-ui.yaml, charts/odpi-egeria-lab/templates/env.yaml, charts/odpi-egeria-lab/values.yaml
Further changes to memory allocations, jvm configuration to support investigation and fixes for #235
=> #235 adjust memory settings, jvm configuration

.github/workflows/release.yml, charts/egeria-base/Chart.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-lineage/Chart.yaml, charts/egeria-pts/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
=> Increment versions for prerelease

README.md, config/other/openshift-cluster-monitoring/cluster-monitoring-config.yaml, config/other/openshift-cluster-monitoring/egeria-monitor.yaml, config/other/openshift-cluster-monitoring/user-workload-monitoring-config.yaml, config/other/postgres-operator/postgresql-deployment.yaml, config/other/prometheus/prometheus.yml, config/values/lab-actuator.yaml, config/values/lab-alwayspull.yaml, config/values/lab-customimages.yaml, config/values/lab-customnodeports.yaml, config/values/lab-graph.yaml, config/values/lab-jdbcdb2.yaml, config/values/lab-jdbcpostgres.yaml, config/values/lab-jupyterdebug.yaml, config/values/lab-mainversion.yaml, config/values/lab-resources.yaml, config/values/lab-strimziconnector.yaml, config/values/lab-xtdb.yaml, config/values/lab-yourkit.yaml
This PR adds a new directory 'config' which contains various configuration files & values snippets that may be useful to chart users
=> #245 add configuration snippets

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
* Updates react UI in base & lab charts
* Fixes blank screen in REX on clicking on a node
* Updates to current self-signed certs
* Prerelease version updated for release
=> Updated reactUI to fix certs & blank screen on detail

charts/egeria-pts/Chart.yaml, charts/egeria-pts/scripts/config-egeria.sh
Fixes PTS
.. when additional capability had been merged in from CTS, the wrong env. variables had been used.
=> #215 Fix PTS - correct TUT endpoint

charts/egeria-base/Chart.yaml, charts/egeria-base/templates/NOTES.txt, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/templates/NOTES.txt, charts/odpi-egeria-lab/values.yaml
Upgrades lab chart to use EgeriaUI 4.1.2 - should fix https://github.com/odpi/egeria-ui/issues/480
=> Upgrade Egeria UI to 4.1.2

charts/egeria-base/Chart.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-lineage/Chart.yaml, charts/egeria-pts/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml
Alternate final 4.0 release which retains existing pre-release UI code as container is not available
=> Update to final 4.0 chart release

charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
Change defaults to run single kafka/zookpr replica in lab-chart
=> odpi-egeria-lab v4.0.2

charts/egeria-cts/Chart.yaml
=> cts chart pre-relase version bump

charts/egeria-server/.helmignore, charts/egeria-server/Chart.yaml, charts/egeria-server/README.MD, charts/egeria-server/files/cocoMDS1.json, charts/egeria-server/files/cocoMDS1.yml, charts/egeria-server/templates/NOTES.txt, charts/egeria-server/templates/_helpers.tpl, charts/egeria-server/templates/config.yaml, charts/egeria-server/templates/deployment.yaml, charts/egeria-server/templates/hpa.yaml, charts/egeria-server/templates/ingress.yaml, charts/egeria-server/templates/service.yaml, charts/egeria-server/templates/serviceaccount.yaml, charts/egeria-server/templates/tests/test-connection.yaml, charts/egeria-server/values.yaml
=> Omag server chart

charts/egeria-base/Chart.yaml, charts/egeria-base/values.yaml, charts/egeria-cts/Chart.yaml, charts/egeria-cts/templates/kafka-cluster.yaml, charts/egeria-cts/values.yaml, charts/egeria-pts/Chart.yaml, charts/egeria-pts/templates/kafka-cluster.yaml, charts/egeria-pts/values.yaml, charts/egeria-server/Chart.yaml, charts/odpi-egeria-lab/Chart.yaml, charts/odpi-egeria-lab/values.yaml
=> Version 4.3
