.gitignore
charts/egeria-base/Chart.yaml
charts/egeria-base/templates/NOTES.txt
charts/egeria-base/templates/config.yaml
charts/egeria-base/templates/env.yaml
charts/egeria-base/templates/presentation.yaml
charts/egeria-base/values.yaml

- Configuration of the default egeria configuration (mds1, view1 etc) via the initialization job is now performed asynchronously after chart installed. This is done by removing the hook specification. The rationale is to make the UX clearer since this is a demo environment. A long 10 minute wait with no output is disconcerting. The original behaviour can be restored with `options.jobs.config.usehook=true`
- Configuration can be disabled by `egeria.config=false` - this allows existing tutorials to use the k8s deployment as a base - since it comes with a single platform and presentation server UI. Note that in this case no scripts are run, though the presentation server configuration is still set to use 'org' as the organization name, and 'mds1' to point to the backend server ie …

Optionally run configuration for egeria-base

---

README.md

Fixes: #86 
URL to link to main egeria docs for k8s updated

#86 correct link to main egeria kubernetes docs

---

charts/egeria-base/Chart.yaml
charts/egeria-base/templates/config.yaml
charts/egeria-base/templates/platform.yaml
charts/egeria-base/templates/presentation.yaml
charts/egeria-base/values.yaml
charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/templates/egeria-core.yaml
charts/odpi-egeria-lab/templates/egeria-datalake.yaml
charts/odpi-egeria-lab/templates/egeria-dev.yaml
charts/odpi-egeria-lab/templates/egeria-factory.yaml
charts/odpi-egeria-lab/templates/egeria-nginx.yaml
charts/odpi-egeria-lab/templates/egeria-presentation.yaml
charts/odpi-egeria-lab/templates/egeria-ui.yaml
charts/odpi-egeria-lab/templates/egeria-uistatic.yaml
charts/odpi-egeria-lab/templates/jupyter.yaml
charts/odpi-egeria-lab/values.yaml

For 
* odpi-egeria-lab
* egeria-base
The following changes were made:
* Default 'pullPolicy' tag is no longer defined by default (replaced by comment)
* If a imageDefaults pullPolicy, or image specific pull policy is set, this is respected as before
* If no pullPolicy is explicitly set (now the default)
- For egeria images (egeria/configure/jupyer) we use 'Always' if the image tag ends in '-SNAPSHOT', otherwise we use 'IfNotPresent'
- Similarly for the presentation server, but we look for '-rc' in the version string
- We default to 'IfNotPresent' for egeria-ui (static component) as there is no identifier in the version distringuishing between a snapshot/release candidate and a final release. This can still be overriden as before
- …

#76 Set pullPolicy automatically

---

charts/egeria-base/Chart.yaml
charts/egeria-base/templates/_helpers.tpl
charts/egeria-base/templates/config.yaml
charts/egeria-base/templates/env.yaml
charts/egeria-base/templates/kafka-cluster.yaml
charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/etc/default.conf.template
charts/odpi-egeria-lab/etc/staticui.conf.template
charts/odpi-egeria-lab/templates/_helpers.tpl
charts/odpi-egeria-lab/templates/egeria-nginx.yaml
charts/odpi-egeria-lab/templates/egeria-uistatic.yaml
charts/odpi-egeria-lab/templates/jupyter.yaml
charts/odpi-egeria-lab/templates/kafka-cluster.yaml
charts/odpi-egeria-lab/templates/rbac.yaml
charts/odpi-egeria-lab/templates/serviceAccount.yaml
charts/odpi-egeria-lab/values.yaml

* #101
- Updates egeria-base chart to use 'strimzi' for kafka
* #18
- Updates egeria-base chart to work within the default, restricted security context on openshift 
- Updates nginx to run unpriviliged (no extra k8s privileges needed) 
- Updates egeria-ui container to run unpriviliged (see also https://github.com/odpi/egeria-ui/issues/289 )
- Updates strimzi config (above) to not require priv
- Removes fsGroup override from jupyter container, to also allow unpriv use (see odpi/egeria#6049 )
- updates chart to use new jupyter image
- adds serviceAccount to enable extra permissions to be added if needed
* Also
- increments chart versions for affected charts

Use strimzi for egeria-base chart

---

charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/templates/egeria-nginx.yaml
charts/odpi-egeria-lab/templates/egeria-uistatic.yaml

After nginx configuration changes some internal ports were mismatching breaking the Egeria UI configuration.
These changes were tested locally running microk8s on mac x86-64
Signed-off-by: Ljupcho Palashevski <ljupcho.palashevski@ing.com>

Use matching ports

---

charts/egeria-base/Chart.yaml
charts/odpi-egeria-lab/Chart.yaml

odpi-egeria-lab, egeria-base are released at 3.4.1
Now supports Apple silicon / m1 / arm64 
- all Egeria containers available in amd64 & arm64
- migrated Kafka support to Strimzi

Release charts 3.4.1

---

charts/egeria-cts/Chart.yaml
charts/egeria-cts/values.yaml
charts/egeria-pts/Chart.yaml
charts/egeria-pts/values.yaml

Reduces mem/cpu min requirement spec for CTS/PTS to 1 core / 4Gb ram (from 2 cores / 8 Gb ram). This is only a min 
spec to allow for scheduling, and can be overriden.
Using these values for testing release on openshift (for CTS at least)

#130 reduce resource requirement spec for cts/pts

---

charts/egeria-cts/Chart.yaml
charts/egeria-cts/scripts/config-egeria.sh
charts/egeria-pts/Chart.yaml
charts/egeria-pts/scripts/config-egeria.sh

Adds support for the in-memory-repository used for cts/pts
Note: Only cts tested as part of the release process.

#138 add support for in-memory-repository to cts/pts charts

---

charts/egeria-cts/Chart.yaml
charts/egeria-cts/scripts/run-cts.sh
charts/egeria-cts/templates/env.yaml
charts/egeria-cts/values.yaml
charts/egeria-pts/Chart.yaml
charts/egeria-pts/scripts/run-pts.sh
charts/egeria-pts/templates/env.yaml
charts/egeria-pts/values.yaml

Adds configurable delay (default 10s) between launch of cts/pts & tut
Value that can be set is 'egeria.delay'

 add configurable delay between cts/pts & tut to improve reliability

---

charts/egeria-base/Chart.yaml
charts/egeria-base/values.yaml
charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/values.yaml

* Updates react UI to 3.8.0-rc.0 (the 3.7 version could not work due to cert validation)
* Updates version to 3.7.1-prerelease.0 for testing
* Expected to only release chart with the new UI in the 3.8 stream

#147 new prelease with updated react UI

---

charts/egeria-base/Chart.yaml
charts/egeria-base/values.yaml
charts/egeria-cts/Chart.yaml
charts/egeria-cts/values.yaml
charts/egeria-pts/Chart.yaml
charts/egeria-pts/values.yaml
charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/values.yaml

First pre-release for egeria 3.8
Note:
- React UI is at 3.8.0-rc.0 (@davidradl I'll start tests with core egeria now, let's update this version when you have a new release)
- Polymer UI is at 3.2.0 (@sarbull @lpalashevski )

odpi/egeria#6435 First prerelease version for the 3.8 release

---

charts/egeria-base/Chart.yaml
charts/egeria-base/templates/kafka-cluster.yaml
charts/egeria-cts/Chart.yaml
charts/egeria-cts/templates/kafka-cluster.yaml
charts/egeria-pts/Chart.yaml
charts/egeria-pts/templates/kafka-cluster.yaml
charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/templates/kafka-cluster.yaml
charts/odpi-egeria-lab/values.yaml

* Corrects version of jupyter container image (this is an egeria customized version) to align with egeria release by default
* Adds securityContext for kafka/zookeeper pods created by Strimzi to ensure works ok in clean OpenShift 4.10 install
* Bumps version

3.9.0 fixes - jupyter & security context

---

charts/egeria-base/Chart.yaml
charts/egeria-base/templates/platform.yaml
charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/templates/_helpers.tpl
charts/odpi-egeria-lab/templates/egeria-core.yaml
charts/odpi-egeria-lab/templates/egeria-datalake.yaml
charts/odpi-egeria-lab/templates/egeria-dev.yaml
charts/odpi-egeria-lab/templates/egeria-factory.yaml

Fixes: #158
- Adds security context for egeria platform containers. This ensures any volumes are mounted with the correct permissions, and are therefore writeable.
- Bumps version to 3.9.2 for incremental release
Tested in:
- Openshift 4.10
- Rancher desktop 1.4.1 / k8s 1.24.1

Set security context for egeria containers

---

charts/egeria-base/Chart.yaml
charts/egeria-base/values.yaml
charts/egeria-cts/Chart.yaml
charts/egeria-cts/values.yaml
charts/egeria-pts/Chart.yaml
charts/egeria-pts/values.yaml
charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/values.yaml

This change allows strimzi to *optionally* be installed alongside any of our helm charts
This is needed when either
* The user installing does not have admin rights to the cluster - for example they are a regular user given access to a namespace just to deploy apps
* You want to install multiple versions of the egeria helm charts - for example when testing/debugging, or running a long-running cts whilst continuing with dev work!
Strimzi installs some cluster-scoped resources which a) are cluster-scoped ie global, and so cannot clash with namespace local and b) require higher permissions - again, due to their scope.
In both cases the strimzi operator should be installed first, manually. This can be done by following the [official …

#117 make strimzi install optional (for multiple per cluster)

---

charts/egeria-base/templates/kafka-cluster.yaml
charts/egeria-base/templates/platform.yaml
charts/egeria-cts/templates/kafka-cluster.yaml
charts/egeria-pts/templates/kafka-cluster.yaml
charts/odpi-egeria-lab/templates/_helpers.tpl
charts/odpi-egeria-lab/templates/kafka-cluster.yaml

Resets securityContext to {}
Fixes #156 properly, but see egeria-docs for update to document that the 'default' namespace should not be used

#156 set securityContext to {}

---

charts/egeria-cts/Chart.yaml
charts/egeria-cts/values.yaml
charts/egeria-pts/Chart.yaml
charts/egeria-pts/values.yaml

* Quote version of egeria images used in pts/cts charts (trailing 0 of 3.10 is stripped .....)
* update version

odpi/egeria#6554 quote version for cts/pts egeria - trailing 0

---

charts/egeria-base/templates/platform.yaml
charts/egeria-base/templates/presentation.yaml
charts/egeria-cts/templates/platform.yaml
charts/egeria-pts/templates/pts.yaml
charts/egeria-pts/templates/tut.yaml
charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/templates/egeria-core.yaml
charts/odpi-egeria-lab/templates/egeria-datalake.yaml
charts/odpi-egeria-lab/templates/egeria-dev.yaml
charts/odpi-egeria-lab/templates/egeria-factory.yaml
charts/odpi-egeria-lab/templates/egeria-nginx.yaml
charts/odpi-egeria-lab/templates/egeria-presentation.yaml
charts/odpi-egeria-lab/templates/egeria-ui.yaml
charts/odpi-egeria-lab/templates/egeria-uistatic.yaml
charts/odpi-egeria-lab/templates/jupyter.yaml
charts/odpi-egeria-lab/values.yaml

Now supports dynamic downloading of additional connectors to egeria platforms - for example xtdb, strimzi etc
To use
helm install .......blah blah -f ~/etc/connector.yaml
Where that file contains
```
downloads:
- url: https://search.maven.org/remotecontent?filepath=org/odpi/egeria/egeria-connector-xtdb/3.9/egeria-connector-xtdb-3.9-jar-with-dependencies.jar
filename: egeria-connector-xtdb-3.9-jar-with-dependencies.jar
```
Multiple connectors can be specified
Done
- lab chart
- base chart
This replaces PR #127 
This makes it easier to experiment with new notebooks that make use of any of the egeria connectors, open source or proprietary. If we add notebooks to coco Pharma that require these connectors, we may update the defaults for …

#3 Allow additional connectors to be downloaded

---

charts/egeria-base/Chart.yaml
charts/egeria-base/templates/env.yaml
charts/egeria-base/templates/platform.yaml
charts/egeria-base/values.yaml
charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/templates/egeria-core.yaml
charts/odpi-egeria-lab/templates/egeria-datalake.yaml
charts/odpi-egeria-lab/templates/egeria-dev.yaml
charts/odpi-egeria-lab/templates/egeria-factory.yaml
charts/odpi-egeria-lab/values.yaml

* Updates to fix connector downloading (some files were not checked in)
* Changed 'downloads' to 'extralibs' -- we've talked about other kinds of downloads, which would need to be put in other places. this makes it clearer that these files will be added into the class path of the server chassis
* Moved the mount directory from /opt/egeria/connectors to /deployments/server/extralib. to be alongside the regular lib directory in the UBI-8 openjdk container
Behaviour if bad connector specified:
Pod will show an init error:
```
egeria-base-platform-0                      0/1     Init:Error          0          33s
```
Pod log will show how curl (used to download connector) failed ie:
```
kubectl logs egeria-base-platform-0 -c …
```

Updates for connector downloading

---

charts/egeria-base/Chart.yaml
charts/egeria-base/templates/kafka-cluster.yaml
charts/egeria-cts/Chart.yaml
charts/egeria-cts/templates/kafka-cluster.yaml
charts/egeria-pts/Chart.yaml
charts/egeria-pts/templates/kafka-cluster.yaml
charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/templates/kafka-cluster.yaml

* Updates kafka version in custom resource for each chart to 3.2.0 (close to egeria build which is 3.2.1)
* Removes hardcoded formats - these will default correctly based on kafka version
* Updates chart versions for publish/test

odpi/egeria#6812 Update kafka version to match strimzi

---

charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/templates/jupyter.yaml
charts/odpi-egeria-lab/values.yaml

Adds ability to set the initial password for Jupyter notebooks.
The approach is now (in priority order):
**1. Using a Kubernetes secret to manage the password**
If value`jupyter.tokenSecret` is set, it must refer to the name of the secret in the current namespace which contains a single key `password` with the value set to the value required
For example:
```
kubectl create secret generic jupyter-lab-secret --from-literal=password='s3cr3t!'
helm install lab egeria/odpi-egeria-lab  --set jupyter.tokenSecret=jupyter-lab-secret
```
**2. Using a password literal**
If value `jupyter.tokenPlain` is set, it is used as the literal password for jupyter. 
for example:
```
helm install lab egeria/odpi-egeria-lab  --set …
```

#179 add option to set password for jupyter

---

charts/egeria-base/templates/platform.yaml
charts/egeria-base/templates/presentation.yaml

Fixes template issue when service.type was set (ie to NodePort)
Template incorrectly stripped a CR, resulting in concatentation & hence invalid yaml

#192 fix platform/presentation template handling of servicePort / CR

---

charts/egeria-base/Chart.yaml
charts/egeria-base/templates/kafka-cluster.yaml
charts/egeria-base/values.yaml
charts/egeria-cts/Chart.yaml
charts/egeria-cts/templates/kafka-cluster.yaml
charts/egeria-cts/values.yaml
charts/egeria-pts/Chart.yaml
charts/egeria-pts/templates/kafka-cluster.yaml
charts/egeria-pts/values.yaml
charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/templates/kafka-cluster.yaml
charts/odpi-egeria-lab/values.yaml

Initial pre-release for 3.12
- Updates chart versions to 3.12-prerelease.0
- Updates egeria image to 3.12 (all)
- Updates strimzi to 0.31.1 (all)
- Updates kafka to 3.2.3 (all)
- Updates jupyter lab to 3.4.7 (lab)
- Updates egeria polymer UI to 3.2.2 (lab)

odpi/egeria#6898 initial prerelease for 3.12

---

.github/workflows/release.yml
charts/egeria-base/templates/NOTES.txt
charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/scripts/setup-notebooks.sh
charts/odpi-egeria-lab/templates/NOTES.txt
charts/odpi-egeria-lab/templates/jupyter.yaml
charts/odpi-egeria-lab/values.yaml

This PR allows a specific version of the egeria-jupyer-notebooks repository to be checked
out when the jupyter container is launched. this is defined in the yaml for the jupyter deployment.
A tag or branch can be specified by setting 'jupyter.gitTagForNotebooks'. If no value is specified, the the default branch (main) will be used.
In the chart values, the default value for this parm is set to: "main"
So for example, if we wanted to use the 'v313test' tag we'd deploy the chart with:
```
helm install lab odpi-egeria-lab --set jupyter.tokenPlain='s3cr3t!' --set jupyter.gitTagForNotebooks=v313test --set strimzi.enabled=false --devel
```
* Note this depends on https://github.com/odpi/egeria-jupyter-notebooks/actions/runs/3446111657/jobs/ …

#178 allow notebook git tag to be specified for checkout

---

charts/egeria-base/Chart.yaml
charts/egeria-base/templates/kafka-cluster.yaml
charts/egeria-cts/Chart.yaml
charts/egeria-cts/templates/kafka-cluster.yaml
charts/egeria-pts/Chart.yaml
charts/egeria-pts/templates/kafka-cluster.yaml
charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/templates/kafka-cluster.yaml
charts/odpi-egeria-lab/values.yaml

- Update strimzi kafka version to 3.3.1 (Tested using odpi-egeria-lab chart)
- Fix tag for jupyter notebooks to V314

prerelease.1, updates to kafka v3.3.1

---

README.md
charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/templates/egeria-core.yaml
charts/odpi-egeria-lab/templates/egeria-datalake.yaml
charts/odpi-egeria-lab/templates/egeria-dev.yaml
charts/odpi-egeria-lab/templates/egeria-factory.yaml
charts/odpi-egeria-lab/templates/egeria-ui.yaml
charts/odpi-egeria-lab/values.yaml
config/values/lab-jvmoptsmemdebug.yaml
config/values/lab-nodeport.yaml

Investigation continues in #235
For now, resources will be unlimited by default, so subject to whatever the container environment deems suitable.
JVM settings will also be reverted by default
Resource limits & jvm configuration can be applied using one of the sample fragments in config/values
Increment version

Revert to defaults for resources

---

charts/egeria-base/Chart.yaml
charts/egeria-base/templates/kafka-cluster.yaml
charts/egeria-base/templates/platform.yaml
charts/egeria-base/values.yaml
charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/templates/egeria-core.yaml
charts/odpi-egeria-lab/templates/egeria-datalake.yaml
charts/odpi-egeria-lab/templates/egeria-dev.yaml
charts/odpi-egeria-lab/templates/egeria-factory.yaml
charts/odpi-egeria-lab/templates/jupyter.yaml
charts/odpi-egeria-lab/templates/kafka-cluster.yaml
charts/odpi-egeria-lab/values.yaml
config/values/lab-storageclass.yaml

* Adds support for specification of storage class
* Adds simple example
To use
```
helm install <blah blah> --set storageClassName='ibmc-vpc-block-general-purpose'
```
or
```
helm install <blah blah> -f config/values/lab-storageclass.yaml
```
The same storageclass will be used for all allocations. No other customizations are possible.
This has been implemented in base & lab charts

#119 add support for storage class

---

charts/odpi-egeria-lab/templates/egeria-ui.yaml
charts/odpi-egeria-lab/values.yaml

- Updated egeria version to 4.1-snapshot for preliminary testing
- Setting tomcat port to 8443 for ui-chassis-spring container to have it working with the lab chart again. This is due to latest changes where we have application.properties available externally in the spring loader path causing override of server.port property to 9443.

Initial fixes for the new 4.1 release

---

charts/odpi-egeria-lab/Chart.yaml
charts/odpi-egeria-lab/templates/egeria-ui.yaml
charts/odpi-egeria-lab/values.yaml

- Explicitly controlling spring configuration loading for ui-chassis-spring application
- loader.path set to empty location 
- Tested using docker and local Kubernetes
Addresses quick fix from previous release + #5918 - Best solution is still to have new dedicated docker image but this is more work since we need to reconsider the assembly structure.
I will explain the solution and the limitations in detail in #5918.

UI platform deployment fixes 

---

charts/egeria-cts/templates/platform.yaml
charts/egeria-cts/values.yaml
charts/egeria-pts/templates/pts.yaml
charts/egeria-pts/values.yaml

* Ability to set JVM_OPTS (additional jvm parameters ie for debugging) values: debug.jvmopts
* Ability to expose port 5005 & activate java agent for IDE debug values: debug.egeriaJVM

#7 add support for debugging to cts/pts

---

charts/egeria-cts/Chart.yaml
charts/egeria-cts/scripts/config-egeria.sh

Reducing servers audit-log severity to Error and Exception.
This should help us troubleshoot the automated CTS run. 
Next we should change it back to default console and add additional file based audit-log destination that always outputs error/exception events only - however this needs additional work on the github action: copy the newly outputted files outside of the container into the pipeline as artifacts.

Add custom audit-log configuration for CTS chart
